name: Postman Test and Allure Report for Duplo merchant

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install newman and newman-reporter-allure
        run: |
          npm install -g newman newman-reporter-allure
          echo "Newman and newman-reporter-allure installed."

      - name: Run Duplo Merchant - API tests
        if: always()
        continue-on-error: true
        run: |
           newman run duplo_merchant_directory/duplo_merchant_collection.json -e "Staging_postman_environment.json" --reporters cli,allure
           echo "Duplo Merchant tests run."

          
          
      - name: Get Duplo Merchant Allure history
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

        
      - name: Duplo Merchant Allure report action
        id: ADMIN_build
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Wait for Duplo Merchant API Allure report to be generated
        if: always()
        continue-on-error: true
        run: sleep 10

      - name: Update Duplo Merchant API Allure Report Widget Title
        continue-on-error: true
        if: steps.build.outcome == 'success'
        run: |
          # Find the latest folder with numerical values in the allure-history directory
          latest_folder=$(find allure-history -mindepth 1 -maxdepth 1 -type d -name '[0-9]*' | sort -n | tail -n 1)

          echo "Latest Folder: $latest_folder"

          # Check if summary.json exists in the latest folder
          summary_path="$latest_folder/widgets/summary.json"
          echo "Summary Path: $summary_path"

          if [[ -e "$summary_path" ]]; then
            # Debug output to check the content before and after the sed command
            cat "$summary_path"  # Print content before

            # Use sed to update the content within the <h2> element
            sudo sed -i 's/Allure Report/Suretree live customer  - API Quality Readiness/' "$summary_path"

            cat "$summary_path"  # Print content after
          else
            echo "Error: summary.json not found in the latest folder."
          fi

      - name: Deploy report to GitHub Pages
        id: deploy
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

    
